<?
$this->headTitle('Параметры');
$this->headTitle('Настройки');
?>
<? $this->headScript()->appendFile($this->basePath('admin/js/settings.js')); ?>
<div class="row">
    <div class="col-lg-6">
        <? $id = 0; ?>
        <? foreach($groups as $group): ?>
            <?
            $settings = $group['settings'];
            $group = $group['group'];
            /* @var $group \Settings\Entity\Groups */
            /* @var $setting \Settings\Entity\Settings */
            ?>
            <? if($id == ceil(count($groups) / 2)): ?>
                </div>
                <div class="col-lg-6">
            <? endif; ?>
            <div id="groupID-<?=$group->getGroupID(); ?>" class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5><?=$group->getName(); ?></h5>
                    <div class="ibox-tools">
                        <? if (count($settings) > 1): ?>
                            <a class="switch-link" data-toggle="tooltip" data-placement="top" data-original-title="Режим сортировки">
                                <i class="fa fa-exchange"></i>
                            </a>
                        <? endif; ?>
                        <a class="collapse-link" data-toggle="tooltip" data-placement="top" data-original-title="Свернуть">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="close-link" data-toggle="tooltip" data-placement="top" data-original-title="Закрыть">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-sm-12 sortable" action="<?=$this->url('admin-settings')?>">
                            <? foreach($settings as $setting):?>
                                <div id="settingID-<?=$setting->getSettingID(); ?>" class="form-group">
                                    <div class="panel panel-primary" style="cursor: move; display: none;">
                                        <div class="panel-heading"><?=$setting->getHeaderName(); ?></div>
                                    </div>
                                    <form method="post" role="form" action="<?=$this->url('admin-settings')?>">
                                        <?=$this->partial('partials/' . $setting->getHtmlControlType(), ['setting' => $setting]); ?>
                                    </form>
                                </div>
                            <? endforeach; ?>
                        </div>
                    </div>
                </div>
            </div>
        <? $id++; endforeach; ?>
    </div>
</div>