<? /* @var $setting \Settings\Entity\Settings */ ?>
<label for="<?=$setting->getName(); ?>" class="control-label"><?=$setting->getHeaderName(); ?></label>
<div class="input-group input-group-sm">
    <input type="text" class="form-control" id="<?=$setting->getName(); ?>" name="<?=$setting->getName(); ?>" value="<?=$setting->getValue(); ?>">
    <span class="input-group-btn">
        <button class="ajaxLoad btn btn-primary" type="submit">Сохранить</button>
    </span>
</div>