<?
/* @var $user \Users\Entity\User */
$user = $this->identity();
$env = (getenv('APP_ENV') == 'development') ? true : false;
?>
<?=$this->doctype(); ?>
<html lang="ru">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <?=$this->headTitle('Система управления сайтом')->setSeparator(' <- ')->setAutoEscape(false); ?>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <? if ($env) {
        $this->headLink()
            ->prependStylesheet($this->basePath('admin/css/style.css'))
            ->prependStylesheet($this->basePath('admin/css/inspinia.css'))
            ->prependStylesheet($this->basePath('admin/css/animate.css'))
            ->prependStylesheet($this->basePath('admin/css/plugins/iCheck/custom.css'))
            ->prependStylesheet($this->basePath('admin/css/plugins/gritter/jquery.gritter.css'))
            ->prependStylesheet($this->basePath('admin/css/plugins/toastr/toastr.css'))
            ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'));
    } else {
        $this->headLink()->prependStylesheet($this->basePath('css/core.css'));
    }
    echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('/admin/img/favicon.ico')], 'PREPEND');
    ?>

    <!--[if lt IE 9]>
    <script src="<?=$this->basePath('js/html5shiv.js')?>"></script>
    <script src="<?=$this->basePath('js/respond.min.js'); ?>"></script>
    <![endif]-->
    <script type="text/javascript">
        var toastrDataArr = [];
    </script>
</head>
<body<?=(isset($_COOKIE['menuPosition']) && $_COOKIE['menuPosition'] == 'mini-navbar') ? ' class="' . $_COOKIE['menuPosition'] . '"' : ''; ?>>
<div id="wrapper">
    <nav class="navbar-default navbar-static-side" role="navigation">
        <div class="sidebar-collapse">
            <ul class="nav metismenu" id="side-menu">
                <li class="nav-header">
                    <div class="profile-element">
                        <span>
                            <img alt="image" class="img-circle" src="<?=$user->getGrAvatar(48); ?>"/>
                        </span>
                        <a href="<?=$this->url('admin-users', ['action' => 'edituser']);?>">
                            <span class="clear">
                                <span class="block m-t-xs">
                                    <strong class="font-bold"><?=$user->getUserFullName();?></strong>
                                </span>
                                <span class="text-muted text-xs block">
                                    <?=$user->getUserRoleLabel(); ?>
                                </span>
                            </span>
                        </a>
                    </div>
                    <div class="logo-element">
                        IN+
                    </div>
                </li>
                <?=$this->navigation('adminPanel')->menu()->setUlClass('nav')->setPartial('partial/admin-navigation.phtml'); ?>
            </ul>

        </div>
    </nav>
    <div id="page-wrapper" class="gray-bg">
        <div class="row border-bottom">
            <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i></a>
                </div>
                <ul class="nav navbar-top-links navbar-right">
                    <?
                    $countAlerts = 0;
                    $countNewMessages = $this->newMessages();
                    if ($countNewMessages > 0)
                        $countAlerts++;
                    ?>
                    <? if ($countAlerts > 0): ?>
                        <li class="dropdown">
                            <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                                <i class="fa fa-bell"></i> <span class="label label-primary"><?=$countAlerts; ?></span>
                            </a>
                            <ul class="dropdown-menu dropdown-alerts">
                                <? if ($countNewMessages > 0): ?>
                                    <li id="countNewMessages">
                                        <a href="<?=$this->url('admin-mail'); ?>">
                                            <div>
                                                <i class="fa fa-envelope fa-fw"></i> У вас <b class="number"><?=$countNewMessages; ?></b>
                                                <?=$this->numEnding($countNewMessages, [' новое', ' новых', ' новых']) .
                                                $this->numEnding($countNewMessages, [' сообщение', ' сообщения', ' сообщений']); ?>
                                            </div>
                                        </a>
                                    </li>
                                <? endif; ?>
                                <?//<li class="divider"></li>?>
                            </ul>
                        </li>
                    <? endif; ?>
                    <li>
                        <?
                        if (isset($this->lockscreen_timeout))
                            $href = $this->url('lock-screen') . '?uri=tosite';
                        else
                            $href = $this->url('home');
                        ?>
                        <a href="<?=$href?>">
                            <i class="fa fa-reply"></i> На сайт
                        </a>
                    </li>
                    <li>
                        <a href="<?=$this->url('logout');?>">
                            <i class="fa fa-sign-out"></i> Выход
                        </a>
                    </li>
                </ul>

            </nav>
        </div>
        <div class="row wrapper border-bottom white-bg page-heading">
            <div class="col-sm-8">
                <h2 id="breadTitle"><?=$this->headTitle()->getContainer()[0]; ?></h2>
                <?=$this->navigation('adminPanel')->breadcrumbs()->setMinDepth(0)->setPartial('partial/admin-breadcrumbs.phtml');?>
            </div>
        </div>

        <div id="contentPage" class="wrapper wrapper-content animated fadeInRight">
            <?php echo $this->content; ?>
        </div>
        <div class="footer">
            <div>
                <strong>Copyright</strong> &copy; <? if (date_format(new \DateTime(), 'Y') == '2015')
                        echo date_format(new \DateTime(), 'Y');
                    else echo '2015 - ' . date_format(new \DateTime(), 'Y');
                    ?> <a href="http://lab-itec.ru/">ООО Лит</a> &laquo;Лаборатория Информационных Технологий&raquo;
            </div>
        </div>

    </div>
</div>

<? if (isset($this->lockscreen_timeout)): ?>
    <script type="text/javascript">
        window.LOCKSCREEN_TIMEOUT = <?=$this->lockscreen_timeout?>;
    </script>
<? $this->headScript()
    ->prependFile($this->basePath('admin/js/lockscreen.js'))
    ->prependFile($this->basePath('admin/js/plugins/idle-timer/idle-timer.min.js'));
endif; ?>

<? if ($env) {
    $this->headScript()
        // Custom and plugin javascript
        ->prependFile($this->basePath('admin/js/inspinia.js'))
        ->prependFile($this->basePath('admin/js/plugins/pace/pace.js'))
        ->prependFile($this->basePath('admin/js/plugins/iCheck/icheck.min.js'))
        // Toastr
        ->prependFile($this->basePath('admin/js/plugins/toastr/toastr.min.js'))
        // Sparkline
        ->prependFile($this->basePath('admin/js/plugins/sparkline/jquery.sparkline.min.js'))
        // GITTER
        ->prependFile($this->basePath('admin/js/plugins/gritter/jquery.gritter.min.js'))
        // Peity
        ->prependFile($this->basePath('admin/js/plugins/peity/jquery.peity.min.js'))
        // Flot
        ->prependFile($this->basePath('admin/js/plugins/flot/jquery.flot.pie.js'))
        ->prependFile($this->basePath('admin/js/plugins/flot/jquery.flot.resize.js'))
        ->prependFile($this->basePath('admin/js/plugins/flot/jquery.flot.spline.js'))
        ->prependFile($this->basePath('admin/js/plugins/flot/jquery.flot.tooltip.min.js'))
        ->prependFile($this->basePath('admin/js/plugins/flot/jquery.flot.js'))
        // Mainly scripts
        ->prependFile($this->basePath('admin/js/plugins/slimscroll/jquery.slimscroll.min.js'))
        ->prependFile($this->basePath('admin/js/plugins/metisMenu/jquery.metisMenu.js'))
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/fixConflictUI.js'))
        ->prependFile($this->basePath('js/plugins/jQueryUI/jquery-ui.min.js'))
        ->prependFile($this->basePath('js/jquery.min.js'));
} else {
    $this->headScript()->prependFile($this->basePath('js/core.js'));
}
echo $this->headScript();
?>
</body>
</html>