<?
if ($this->identity()->getUserRoleId() != \Users\Entity\User::ADMIN_ROLE) {
    $noButton = true;
}
$title = (isset($adduser) && $adduser == true) ? 'Добавить пользователя' : 'Редактировать пользователя';
$this->headTitle($title);
if (!isset($noButton))
    $this->headTitle('Все пользователи');

$this->setCurrentNavigationPage('adminPanel', 'admin-users');
$this->addCurrentBreadCrumb($title, isset($addpage) ? 'fa fa-plus' : 'fa fa-pencil');

//$this->headLink()->appendStylesheet($this->basePath('admin/css/plugins/datapicker/bootstrap-datetimepicker.min.css'));
//$this->headScript()->appendFile($this->basePath('admin/js/plugins/datapicker/moment.js'));
/* @var $form \Admin\Form\EditUser */
?>

<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5><?=$title; ?></h5>
                <div class="ibox-tools">
                    <a href="<?=(!isset($noButton)) ? $this->url('admin-users') : $this->url('admin'); ?>" class="btn btn-default btn-xs" style="color: #fff;">
                        <span class="glyphicon glyphicon-arrow-left"></span>
                        Назад
                    </a>
                    <a class="collapse-link" data-toggle="tooltip" data-placement="top" data-original-title="Свернуть">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="close-link" data-toggle="tooltip" data-placement="top" data-original-title="Закрыть">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>
            <div class="ibox-content">
                <?=$this->form($form, TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL);?>
            </div>
        </div>
    </div>
</div>