<?
$this->headTitle(isset($this->addForm) ? 'Добавить форму' : 'Редактировать форму');
$this->headTitle('Формы');

$this->setCurrentNavigationPage('adminPanel', 'admin-forms');
$this->addCurrentBreadCrumb(isset($this->addForm) ? 'Добавить форму' : 'Редактировать форму', isset($this->addForm) ? 'fa fa-plus' : 'fa fa-pencil');

$this->headLink()->appendStylesheet($this->basePath('css/forms.css'));
?>
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5><?=isset($this->addForm) ? 'Добавить форму' : 'Редактировать форму'?></h5>
                <div class="ibox-tools">
                    <a href="<?=$this->url('admin-forms'); ?>" class="btn btn-default btn-xs" style="color: #fff;">
                        <span class="glyphicon glyphicon-arrow-left"></span>
                        Назад
                    </a>
                    <a class="collapse-link" data-toggle="tooltip" data-placement="top" data-original-title="Свернуть">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="close-link" data-toggle="tooltip" data-placement="top" data-original-title="Закрыть">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>
            <div class="ibox-content">
                <form method="post" class="form-horizontal">
                    <? foreach ($this->form as $params): ?>
                        <?=$this->partial('partials/' . $params['type'], array('params' => $params)); ?>
                    <? endforeach; ?>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-ok"></span> Сохранить</button>
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>
                </form>
            </div>
        </div>
    </div>
</div>