<?
$this->headTitle('Формы');
$this->headLink()->appendStylesheet($this->basePath('css/form-pure.min.css'))
?>
<div class="row">
    <div class="col-sm-12" style="margin-bottom: 10px;">
        <a href="<?=$this->url('admin-forms', ['action' => 'addform']); ?>" class="btn btn-sm btn-info pull-right"><i class="fa fa-plus"></i> Добавить форму</a>
    </div>
</div>
<div class="row">
    <? foreach ($this->forms as $alias => $form): ?>
        <div class="col-lg-4">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h3><?=$form['form_name']; ?></h3>
                </div>
                <div class="ibox-content">
                    <?=$form['form']; ?>
                </div>
                <div class="ibox-footer float-right">
                    <a href="<?=$this->url('admin-forms', ['action' => 'deleteform', 'alias' => $alias])?>" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i> Удалить</a>
                    <a href="<?=$this->url('admin-forms', ['action' => 'editform', 'alias' => $alias])?>" class="btn btn-sm btn-primary"><i class="fa fa-pencil"></i> Редактировать</a>
                </div>
            </div>
        </div>
    <? endforeach; ?>
</div>