<?
if (isset($seo['seo_title']) && $seo['seo_title'] != null)
    $this->headTitle($seo['seo_title']);
if (isset($seo['seo_keywords']) && $seo['seo_keywords'] != null)
    $this->headMeta()->appendName('keywords', $seo['seo_keywords']);
if (isset($seo['seo_description']) && $seo['seo_description'] != null)
    $this->headMeta()->appendName('description', $seo['seo_description']);

/* @var $news \News\Entity\News */
$content = $news->getContent();
$content = str_replace(['{server_url}', '{base_url}'], [$this->serverUrl(), ($this->basePath() == null) ? '/' : $this->basePath()], $content);
?>
<?=$content; ?>