<? $this->headTitle('Меню'); ?>
<? $this->headScript()->appendFile($this->basePath('admin/js/menu.js')); ?>
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <button type="button" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#litAddMenu">
                    <span class="glyphicon glyphicon-plus"></span> Добавить пункт меню
                </button>
                <small>Перетащите для изменения порядка.</small>
                <div class="modal inmodal fade" id="litAddMenu" tabindex="-1" role="dialog" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                                <i class="fa fa-indent modal-icon"></i>
                                <h4 class="modal-title">Добавить пункт меню</h4>
                            </div>
                            <form id="litAddMenuForm" method="post" action="<?=$this->url('admin-menu', ['action' => 'ajax']); ?>">
                                <div class="modal-body">
                                    <div class="form-group">
                                        <label for="label">Текст ссылки</label>
                                        <input type="text" class="form-control" id="label" name="label" value="" placeholder="Текст ссылки" required="required">
                                    </div>
                                    <div class="form-group">
                                        <label for="url">Ссылка</label>
                                        <input type="text" class="form-control" id="url" name="url" value="" placeholder="Ссылка" required="required">
                                    </div>
                                    <div class="form-group">
                                        <label>
                                            <input type="checkbox" class="i-checks" id="active" name="active" value="1" checked="checked">
                                            Активность
                                        </label>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button id="modal-close" type="button" class="btn btn-white" data-dismiss="modal">Закрыть</button>
                                    <button type="submit" class="btn btn-primary">Сохранить</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="ibox-tools">
                    <a class="collapse-link" data-toggle="tooltip" data-placement="top" data-original-title="Свернуть">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="close-link" data-toggle="tooltip" data-placement="top" data-original-title="Закрыть">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>
            <div class="ibox-content">
                <div class="table-responsive">
                    <table id="litSettingsMenu" class="table table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>Текст ссылки</th>
                            <th>Ссылка</th>
                            <th>Активность</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody class="ui-sortable" data-action="<?=$this->url('admin-menu', ['action' => 'ajax']); ?>">
                        <tr id="blank" data-id="" style="display: none">
                            <td class="litEditMenu">
                                <span class="litMenuLabel"></span>
                                <div class="input-group-sm" style="display: none">
                                    <input type="text" class="form-control" name="label" value="">
                                </div>
                            </td>
                            <td class="litEditMenu">
                                <span class="litMenuUrl"></span>
                                <div class="input-group-sm" style="display: none">
                                    <input type="text" class="form-control" name="url" value="">
                                </div>
                            </td>
                            <td class="litEditMenu">
                                <input type="checkbox" class="i-checks-next" value="1">
                            </td>
                            <td class="litEditMenuCell">
                                <button class="btn btn-primary btn-xs litDeleteMenu" type="button" title="Удалить">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </td>
                        </tr>
                        <? /* @var $menuItem \Menu\Entity\Menu */ ?>
                        <? foreach($menu as $menuItem): ?>
                            <tr data-id="<?=$menuItem->getId(); ?>">
                                <td class="litEditMenu">
                                    <span class="litMenuLabel"><?=$menuItem->getLabel(); ?></span>
                                    <div class="input-group-sm" style="display: none">
                                        <input type="text" class="form-control" name="label" value="<?=$menuItem->getLabel(); ?>">
                                    </div>
                                </td>
                                <td class="litEditMenu">
                                    <span class="litMenuUrl"><?=$menuItem->getUrl(); ?></span>
                                    <div class="input-group-sm" style="display: none">
                                        <input type="text" class="form-control" name="url" value="<?=$menuItem->getUrl(); ?>">
                                    </div>
                                </td>
                                <td class="litEditMenuCell">
                                    <input type="checkbox" class="i-checks" value="1"<?=($menuItem->getActive()) ? ' checked="checked"' : ''; ?>>
                                </td>
                                <td class="litEditMenuCell">
                                    <button class="btn btn-primary btn-xs litDeleteMenu" type="button" title="Удалить">
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </button>
                                </td>
                            </tr>
                        <? endforeach; ?>
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
</div>